WIP PR for BXMSDOC-7489: Update and single-source the Building custom dashboard widgets doc based on BAPL-1863, BAPL-1865, and BAPL-1862
kaldesai/kie-docs pull request #114
Opened 2021-04-12 17:33 UTC by kaldesai

Associated JIRA: https://issues.redhat.com/browse/BXMSDOC-7489

**Affected BAPLs for the change:**
- [BAPL-1862](https://issues.redhat.com/browse/BAPL-1862): [Dashbuilder] Prometheus Data Set Provider
- [BAPL-1863](https://issues.redhat.com/browse/BAPL-1863): [Dashbuilder] Kafka Data Set Provider
- [BAPL-1865](https://issues.redhat.com/browse/BAPL-1865): [Dashbuilder] Time Series Displayer

**Enterprise document previews:**
- [RHPAM-IV. Building custom dashboard widgets]()
- [RHDM-IV. Building custom dashboard widgets]()

**Doc impact for enterprise documents:**
- Check section **28. Data source and database driver management** in RHPAM doc

**Community document previews:**
- [jBPM document](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-7493-jBPM-DataSourceMGT/#data-source-management-con_business-processes)

**Doc impact for community documents:**
- Check **13.8.9. Data source and database driver management** in jBPM doc.

Can you please review and verify the community doc and share your feedback?

2021-04-14 11:00 UTC, manaswinidas requested changes
Hi @kaldesai , I've left some comments, please check if they make sense.

2021-04-15 11:02 UTC, hmanwani-rh reviewed
@kaldesai Please check the comments and suggestions below and let me know if you have any questions.

2021-04-15 11:02 UTC, hmanwani-rh commented on doc-content/jbpm-docs/src/main/asciidoc/BAM/proc-creating-time-series-components.adoc
> +|It is a checkbox. By default it is selected. If this component property is selected, you can use the zoom in, zoom out, selection zoom, panning functions of the time series component.
```suggestion
|Select the checkbox to display the toolbar. By default, this checkbox is checked. If this component property is enabled, you can use the zoom in, zoom out, selection zoom, and panning functions of the time series chart component.
```

2021-04-15 11:02 UTC, hmanwani-rh commented on doc-content/jbpm-docs/src/main/asciidoc/BAM/proc-creating-time-series-components.adoc
> +|You can set the chart name as per your requirements. By default it is set to *Newchart*.
```suggestion
|Set the chart name. By default, the chart name is set as *Newchart*.
```

2021-04-19 03:52 UTC, kaldesai commented on doc-content/jbpm-docs/src/main/asciidoc/BAM/proc-creating-time-series-components.adoc
> +|It is a checkbox. By default it is selected. If this component property is selected, you can use the zoom in, zoom out, selection zoom, panning functions of the time series component.
Done.

2021-04-19 03:53 UTC, kaldesai commented on doc-content/jbpm-docs/src/main/asciidoc/BAM/proc-creating-time-series-components.adoc
> +|It is a checkbox. You can zoom in the Y axis.
Added.

2021-04-19 03:53 UTC, kaldesai commented on doc-content/jbpm-docs/src/main/asciidoc/BAM/proc-creating-time-series-components.adoc
> +|It is a checkbox. By default it is selected.
Added

2021-04-19 03:54 UTC, kaldesai commented on doc-content/jbpm-docs/src/main/asciidoc/BAM/proc-creating-time-series-components.adoc
> +|It is a checkbox. You can set the type as a chart, area, or line.
Updated

2021-04-19 03:56 UTC, kaldesai commented on doc-content/jbpm-docs/src/main/asciidoc/BAM/proc-creating-time-series-components.adoc
> +You can export the time series components to Dashbuilder Runtime and retrieve the information from a KIE Server data set. You can also create, edit, and build a dashboard using a time series componen
Updated

2021-04-19 04:00 UTC, kaldesai commented on doc-content/jbpm-docs/src/main/asciidoc/BAM/proc-creating-time-series-components.adoc
> +You can use the time series component to represent your data in the time series data. You can create your own dashboards connected to your time series data sets.
Updated.

2021-04-19 04:00 UTC, kaldesai commented on doc-content/jbpm-docs/src/main/asciidoc/BAM/proc-creating-time-series-components.adoc
> += Creating time series component
Yes, +1 to that. I will change the title of the procedure.

2021-04-19 04:03 UTC, kaldesai commented on doc-content/jbpm-docs/src/main/asciidoc/BAM/con-building-custom-dashboard-reporting-components.adoc
> +|This component is used to display the data from data sets in the form time series.
Yes, that's true. 
Typo :|

2021-04-19 04:06 UTC, kaldesai commented on doc-content/enterprise-only/pages/building-custom-dashboard-widgets-creating-process-heatmap-components-proc.adoc
> +You can modify the SQL query according to your database as per the requirements.
Done

2021-04-19 04:07 UTC, kaldesai commented on doc-content/jbpm-docs/src/main/asciidoc/BAM/con-building-custom-dashboard-components.adoc
> +A page contains different types of components. From the *Components* panel, you can use the following component types in a page:
Updated

2021-04-19 06:16 UTC, manaswinidas approved these changes

2021-04-23 05:49 UTC, sthundat commented on doc-content/enterprise-only/pages/building-custom-dashboard-widgets-creating-all-processes-heatmap-components-proc.adoc
> +. In the *Data* tab, select *NODEID* and *TOTAL_HITS* from the *Columns* field.
Hi @kaldesai ,
for all process heapmap column values are EXTERNALID,PROCESSID,NODEID and TOTAL_HITS

2021-04-23 08:30 UTC, merged