WIP PR for BXMSDOC-8484: Add a section about setting the priority of a task in the Business Central.
kaldesai/kie-docs pull request #137
Opened 2022-06-21 15:33 UTC by kaldesai

Epic: https://issues.redhat.com/browse/BXMSDOC-8483
Tracking JIRA: https://issues.redhat.com/browse/BXMSDOC-8484

Doc preview: [III. Managing and monitoring business processes in Business Central](http://file.pnq.redhat.com/~kaldesai/BXMSDOC-8484-task-priority-RHPAM/#setting-the-priority-of-task-MVEL-proc) 

Doc impact: Please check and verify section **29.6. Setting the priority of a task as an MVEL expression** of the shared document and let me know what you think.

2022-06-21 21:18 UTC, csherrar reviewed
Other than a few questions and suggestions, looks good to me, Kalyani!

2022-06-21 21:18 UTC, csherrar commented on doc-content/enterprise-only/admin-and-config/setting-the-priority-of-task-MVEL-proc.adoc
> +. On the *Task Inbox* page, click the task to open it.
[Style question] - might it be better to refer to the task UI element or perhaps rephrase to "To do this, do that":

s/click the task to open it.
/click the name of the task you want to open.
/click the task name to open the task.
/to open a specific task, click the task name.

2022-06-24 19:55 UTC, LuboTerifaj requested changes
Hello @kaldesai ,

[BAPL-2244](https://issues.redhat.com/browse/BAPL-2244) was actually about enabling expressions in Process Designer editor, not in Task inbox. It is not possible to set expressions in Task Inbox.

2022-06-27 04:02 UTC, kaldesai commented
> Hello @kaldesai ,
> 
> [BAPL-2244](https://issues.redhat.com/browse/BAPL-2244) was actually about enabling expressions in Process Designer editor, not in Task inbox. It is not possible to set expressions in Task Inbox.

Hey @LuboTerifaj 
We confirmed the doc impact from Jamie on the [BAPL-2244](https://issues.redhat.com/browse/BAPL-2244) itself and also received an ack for the content written. Here: [BXMSDOC-8539](https://issues.redhat.com/browse/BXMSDOC-8539)

Can you please let us know what will be the correct location in the doc to include this then?
Doc: [Developing process services in Red Hat Process Automation Manager](https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.12/html-single/developing_process_services_in_red_hat_process_automation_manager/index#viewing-task-variables-advanced-filters-in-bc-proc)

2022-07-01 15:13 UTC, LuboTerifaj commented
Hello @kaldesai,

Unfortunately it is not possible to set expressions in Task Inbox. See my comment in [BXMSDOC-8541](https://issues.redhat.com/browse/BXMSDOC-8541).

Thank you!

2023-01-17 15:42 UTC, LuboTerifaj commented
Hi @kaldesai , any updates? Thanks!

2023-01-18 05:33 UTC, closed without merging